import java.util.Scanner;
class exception3{
    public static void main(String Arg[]){
        try{
            //code
        }
        catch(ArrayIndexOutOfBoundsException obj){

        }
        catch(ArithematicException obj){

        }
        catch(Exception obj){

        }
        finally{
            System.out.println("inside finally block");
        }

    }
}